version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php74:
    build: .
    image: echarts:p74
    privileged: false
    container_name: echartsjson
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    tty: true
